//General
enum Race               { ALTMER, ARGONIAN, BOSMER, BRETON, DUNMER, IMPERIAL, KHAJIIT, NORD, ORC, REDGAURD };
enum Gender             { MALE, FEMALE };
enum Age                { YOUNG, ADULT, MATURE, MIDDLEAGED, ELDER, VENERABLE, AGELESS};
enum Profession         { ACROBAT, AGENT, ARCHER, ASSASSIN, BARBARIAN, BARD, BATTLEMAGE, CRUSADER, HEALER, KNIGHT, MAGE, MONK, NIGHTBLADE, PILGRIM, ROGUE, SCOUT, SORCERER, SPELLSWORD, THIEF, WARRIOR, WITCHHUNTER };
enum BirthSign          { THEAPPRENTICE, THEATRONACH, THELADY, THELORD, THELOVER, THEMAGE, THERITUAL, THESERPENT, THESHADOW, THESTEED, THETHIEF, THETOWER, THEWARRIOR };
enum Supernatural       { NONE, VAMPIRE, WAREWOLF };
enum Apparel            { CLOTHING, ROBES, LIGHTARMOUR, HEAVYARMOUR };
enum CombatStyle        { MARKSMAN, ONEHANDED, TWOHANDED, DESTRUCTION };

//Skills
enum MainSkill          { ALTERATION, CONJURATION, DESTRUCTION, ILLUSION, RESTORATION, RANGED, BLOCK, HEAVYARMOR, ONEHANDED, LIGHTARMOR, DEXTERITY, WAYFARER, SNEAK, SPEACH, TWOHANDED };
enum SecondarySkill     { ALTERATION, CONJURATION, DESTRUCTION, ILLUSION, RESTORATION, RANGED, BLOCK, HEAVYARMOR, ONEHANDED, LIGHTARMOR, DEXTERITY, WAYFARER, SNEAK, SPEACH, TWOHANDED };
enum CraftingSkill      { ENCHANTING, SMITHING, ALCHEMY };

//Personalality
enum Ethics             {};
enum Morality           {};
enum Temperment         {};
enum Tendency           {};
enum Demeanor           {};
enum Sanity             {};
enum Motivation         {};
enum Deity              {};
enum Piety              {};
enum Habit              {};
enum Hobby              {};
enum Interest           {};

//Appearance
enum Weight             {};
enum Skintone           {};
enum Complexion         {};
enum Scars              {};
enum Warpaint           {};
enum WarpaintColor      {};
enum EyeColor           {};
enum HairSyle           {};
enum FacialHair         {};
enum HairColor          {};

//Racism
enum AltmerFeelings     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum ArgonianFeelings   { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum BosmerFeelings     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum BretonFeelings     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum DunmerFeelings     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum ImperialFeelings   { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum KhajiitFeelings    { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum NordFeelings       { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum OrcFeelings        { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum RedguardFeelings   { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };

//Agism
enum ChildrenFeelings  { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum EldersFeelings    { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };

//Factions
enum Blades           { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum GreyBeards       { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum Imperials        { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum Stormcloaks      { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum Companions       { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum DarkBrotherhood  { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum MageGuild        { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum ThievesGuild     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum BardsGuild       { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum Dawnguard        { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
enum VolkiharClan     { HOSTILE, DISLIKE, TOLERANT, INDIFFERENT, FRIENDLY, ADORING, ZEALOT };
